name: TestWorkflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run workflow generator
        uses: mayank1809/workflow@main

        
